# Generated by Django 4.1.5 on 2023-03-05 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0002_remove_master_email_remove_student_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='confirmpassword',
        ),
        migrations.RemoveField(
            model_name='master',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='confirmpassword',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
