# Generated by Django 4.1.5 on 2023-03-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0003_remove_master_confirmpassword_remove_master_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='confirmpassword',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='master',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='confirmpassword',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
