# Generated by Django 4.1.5 on 2023-03-05 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0004_master_confirmpassword_master_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='confirmpassword',
        ),
        migrations.RemoveField(
            model_name='student',
            name='confirmpassword',
        ),
    ]
