# Generated by Django 4.1.5 on 2023-03-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0006_master_confirmpassword_student_confirmpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20)),
                ('task', models.CharField(default='', max_length=50)),
                ('answer', models.CharField(default='', max_length=10)),
                ('result', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
